function generateSettleStatement(obj,filename,timeNum)
    if nargin == 1
        tn = now;
        path = strcat('SettleStatement_',datestr(tn,'yyyymmddHHMMSS'),'.txt');
    elseif nargin == 2
        tn = now;
        path = filename;
    elseif nargin == 3
        tn = timeNum;
        path = filename;
    else
        obj.m_Log.printCrucial('Error! generateSettleStatement() only accept 0/1/2 input arguments.');
        return;
    end
    obj.m_Log.printInfo('Generate settle statement %s ......',path);
    %
    fid = fopen(path,'a');
    % output capital infomation
    fprintf(fid,'-----------------------------------------------------------------------------\r\n');
    fprintf(fid,'-----------------------------Capital Infomation------------------------------\r\n');
    fprintf(fid,'-----------------------------------------------------------------------------\r\n');
    fprintf(fid,'%-20s %12s %12s %12s %12s %12s %13s %12s %8s\r\n', ...
                'DateTime','Deposit','Settle','Balance','Margin', ...
                'FreeMoney','ClosePosiGain','OpenPosiGain','Fee');
    fprintf(fid,'%-20s %12.2f %12.2f %12.2f %12.2f %12.2f %13.2f %12.2f %8.2f\r\n', ...
                 datestr(tn), ...
                 obj.m_Capital.deposit, ...
                 obj.m_Capital.settle, ...
                 obj.m_Capital.balance, ...
                 abs(obj.m_Capital.margin), ...
                 obj.m_Capital.freeMoney, ...
                 obj.m_Capital.closePosiGain, ...
                 obj.m_Capital.openPosiGain, ...
                 obj.m_Capital.fee);
    % output position infomation
    fprintf(fid,'-----------------------------------------------------------------------------\r\n');
    fprintf(fid,'----------------------------Position Infomation------------------------------\r\n');
    fprintf(fid,'-----------------------------------------------------------------------------\r\n');
    fprintf(fid,'%-6s %-9s %8s %8s %13s %12s %12s %12s\r\n', ...
                'Symbol','BuyOrSell','TotalNum','TodayNum', ...
                'AllowCloseNum','AveragePrice','Profit','Margin');
    for i=1:length(obj.m_PosiBox)
        fprintf(fid,'%-6s %-9s %8d %8d %13d %12.2f %12.2f %12.2f\r\n', ...
                    obj.m_PosiBox(i).instID, ...
                    obj.m_PosiBox(i).buysell, ...
                    int32(obj.m_PosiBox(i).totalNum), ...
                    int32(obj.m_PosiBox(i).todayNum), ...
                    int32(obj.m_PosiBox(i).allowCloseNum), ...
                    obj.m_PosiBox(i).avgPrice, ...
                    obj.m_PosiBox(i).profit, ...
                    obj.m_PosiBox(i).margin);
    end
    % output trade order records
    todayRcdNum = 0;
    for i = obj.m_Index.trdBoxDayBeginIdx : length(obj.m_TradeBox)
        todayRcdNum = todayRcdNum + 1;
        if todayRcdNum == 1
            fprintf(fid,'-----------------------------------------------------------------------------\r\n');             
            fprintf(fid,'--------------------------Trade Orders Infomation----------------------------\r\n');
            fprintf(fid,'-----------------------------------------------------------------------------\r\n');
            fprintf(fid,'%-6s %-9s %-7s %8s %8s %-20s %8s %8s\r\n', ...
                        'Symbol','OpenClose','BuySell','Price', ...
                        'Lots','Time','SL_Price','TP_Price');
        end
        fprintf(fid,'%-6s %-9s %-7s %8.2f %8d %-20s %8.2f %8.2f\r\n', ...
                    obj.m_TradeBox(i).instID, ...
                    obj.m_TradeBox(i).openclose, ...
                    obj.m_TradeBox(i).buysell, ...
                    obj.m_TradeBox(i).openPrice, ...
                    obj.m_TradeBox(i).lot, ...
                    datestr(obj.m_TradeBox(i).openTime), ...
                    obj.m_TradeBox(i).slPrice, ...
                    obj.m_TradeBox(i).tpPrice);
        
    end
    % output close order records
    todayRcdNum = 0;
    for i = obj.m_Index.clsBoxDayBeginIdx : length(obj.m_CloseBox)
        todayRcdNum = todayRcdNum + 1;
        if todayRcdNum == 1
            fprintf(fid,'-----------------------------------------------------------------------------\r\n');             
            fprintf(fid,'--------------------------Close Orders Infomation----------------------------\r\n');
            fprintf(fid,'-----------------------------------------------------------------------------\r\n');
            fprintf(fid,'%-6s %-20s %-20s %10s %10s %10s %10s\r\n', ...
                        'Symbol','OpenTime','CloseTime','OpenPrice', ...
                        'ClosePrice','Lots','Profit');
        end
        fprintf(fid,'%-6s %-20s %-20s %10.2f %10.2f %10d %10.2f\r\n', ...
                     obj.m_CloseBox(i).instID, ...
                     datestr(obj.m_CloseBox(i).openTime), ...
                     datestr(obj.m_CloseBox(i).closeTime), ...
                     obj.m_CloseBox(i).openPrice, ...
                     obj.m_CloseBox(i).closePrice, ...
                     obj.m_CloseBox(i).lot, ...
                     obj.m_CloseBox(i).profit);
    end
    %
    fclose(fid);
end