classdef EnumType < int32
    enumeration
      NONE           (0)
      OPEN           (1)
      HIGH           (2)
      LOW            (3)
      CLOSE          (4)
      VOLUME         (5)
      TURNOVER       (6)
      BUY            (7)
      SELL           (8)
      NOW            (10)
      DAY            (11)
      HOUR           (12)
      TXT            (13)
      STDIO          (14)
      XLSX           (15)
      DATABASE       (16)
      TODAY          (17)
      FAK            (18)
      FOK            (19)
      ON             (20)
      OFF            (21)
      UP             (22)
      DOWN           (23)
      TRUE           (24)
      FALSE          (25)
      TICK           (26)
      M1             (27)
      M5             (28)
      M15            (29)
      M30            (30)
      H1             (31)
      H2             (32)
      H4             (33)
      D1             (34)
      W1             (35)
      DATESTR        (36)
      DATENUM        (37)
      MINUTE         (38)
    end
end